### ISSUE TITLE
Why don't :setq, :custom, etc. distribute when normalizing?

### ISSUE THREAD

**Issue by d125q** [conao3/leaf.el#279]
I would expect

```elisp
(leaf some-package
  :custom
  ((to-enable-1 to-enable-2 to-enable-3) . t)
  ((to-disable-1 to-disable-2 to-disable-3) . nil))
```

to expand to

```elisp
(prog1 'some-package
  (leaf-handler-leaf-protect some-package
    (custom-set-variables
     '(to-enable-1 t "Customized with leaf in some-package block")
     '(to-enable-2 t "Customized with leaf in some-package block")
     '(to-enable-3 t "Customized with leaf in some-package block")
     '(to-disable-1 nil "Customized with leaf in some-package block")
     '(to-disable-2 nil "Customized with leaf in some-package block")
     '(to-disable-3 nil "Customized with leaf in some-package block"))))
```

However, it currently expands to

```elisp
(prog1 'some-package
  (leaf-handler-leaf-protect some-package
    (custom-set-variables
     '((to-enable-1 to-enable-2 to-enable-3)
       t "Customized with leaf in some-package block")
     '((to-disable-1 to-disable-2 to-disable-3)
       nil "Customized with leaf in some-package block"))))
```

I cannot think of a scenario where I would **not** want to distribute the value when normalizing the lists.  Any ideas?

**Comment by conao3** [comment]
Since you can do that with `:hook`, it makes sense to expect distribution with `:setq` and `:custom`, and you can see that this is desirable in terms of keyword balance.
Actually, that was possible in the previous `leaf`, but it turned out that it didn't work in the corner case, so the feature was removed.

see #132 and see removed test cases https://github.com/conao3/leaf.el/pull/136/files#diff-2e252190fe09cfad97031fe62dfc4e8f
(I solve this issue by using `leaf-nil` instead of `nil`, but the solution is reverted. So I solve this issue by feature removed)

The feature was left out, but I think it's possible to have a subset of the old `leaf` feature that doesn't support configuration nesting.

**Comment by conao3** [comment]
You can see develop branch at branch named `feature#279`.
This develop branch will merge after passing those commented out test case https://github.com/conao3/leaf.el/compare/feature%23279?expand=1#diff-2e252190fe09cfad97031fe62dfc4e8f

**Comment by conao3** [comment]
I develop it but you also can PR to this working branch instead of master to merge fast.

**Comment by conao3** [comment]
(oops. I closed this issue. reopen.)
merged! please test HEAD.

**Comment by d125q** [comment]
Seems to be working well for my uses cases!  Closing the issue.  Thank you!

**Comment by conao3** [comment]
Good. Thanks for this suggestion!
