### ISSUE TITLE
Using :leaf-defer like :defer in use-package?

### ISSUE THREAD

**Issue by alecStewart1** [conao3/leaf.el#501]
## Description

I was looking into switching to leaf from use-package, and I was wondering if I can use `:leaf-defer` like how you can use `:defer` in use-package.

In the sense of you can pass either `t` or a number that specifies how long after startup you want the package loaded.

Looking a little bit at the source code, I would assume not, but I thought I'd ask anyways. Below are some basic examples of what I'd like to do.

## Examples

```elisp
;;;; Simple (using `t')
;;;;

(leaf simple
  :ensure nil
  :leaf-defer t
  :custom
  (idle-update-delay                   . 1.2)
  (blink-matching-paren                . nil)
  (track-eol                           . t)
  (completion-show-help                . nil)
  (column-number-mode                  . t)
  (line-number-mode                    . t)
  (kill-do-not-save-duplicates         . t)
  (save-interprogram-paste-before-kill . t)
  (delete-trailing-lines               . nil)
  (set-mark-command-repeat-pop         . t)
  (kill-ring-max                       . 30000))

;;;; Bookmark (using a number)
;;;;

(leaf bookmark
  :ensure nil
  :leaf-defer 0.1
  :custom
  `((bookmark-default-file . ,(concat my-etc-dir "bookmarks"))
    (bookmark-save-flag    . t)))

```

**Comment by conao3** [comment]
There is no `:defer` keyword in `leaf`. All packages are automatically defer-loaded by `leaf`.
The user only needs to tell `leaf` if they do not want to lazy load. You can set `:leaf-defer` to `nil`.
In other words, `use-package-always-defer` is in the `t` state.

`leaf` has no `:defer` keyword, so there is no way to specify a delay time in the first place. This is intentional.
Packages that are loaded on a timer with a delay time are difficult to debug and do not contribute much to usability.

In your first example, you can simply omit the `:leaf-defer t`. This is already implicitly set for all `leaf`s. see https://github.com/conao3/leaf.el/blob/a4fd520f5c31f54e0797155866e0b35df277664e/leaf.el#L377-L380
In the second example, there is no feature corresponding to leaf.
